#!/bin/sh
# Launches DWM and all software necessary to comprise a desktop environment

setbg &			# set the background
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &	# Polkit auth agent

autostart="xcompmgr dunst pipewire"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

ssh-agent dwm
